# permissions for end users to edit fapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fauli-operator
    app.kubernetes.io/part-of: fauli-operator
    app.kubernetes.io/managed-by: kustomize
  name: fapp-editor-role
rules:
- apiGroups:
  - fauli.sbebe.ch
  resources:
  - fapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fauli.sbebe.ch
  resources:
  - fapps/status
  verbs:
  - get
