---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - fauli.sbebe.ch
  resources:
  - fapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fauli.sbebe.ch
  resources:
  - fapps/finalizers
  verbs:
  - update
- apiGroups:
  - fauli.sbebe.ch
  resources:
  - fapps/status
  verbs:
  - get
  - patch
  - update
