# permissions for end users to edit slothapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: slothapplication-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: sloth-operator
    app.kubernetes.io/part-of: sloth-operator
    app.kubernetes.io/managed-by: kustomize
  name: slothapplication-editor-role
rules:
- apiGroups:
  - sloth.sbebe.ch
  resources:
  - slothapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sloth.sbebe.ch
  resources:
  - slothapplications/status
  verbs:
  - get
