apiVersion: fauli.sbebe.ch/v1alpha1
kind: Fapp
metadata:
  name: fapp-sample
spec:
  replicas: 2
  image: gcr.io/google-samples/hello-app:1.0
  port: 8080
  isExposed: true
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi


  # curl --resolve "fapp.sbebe.ch:8080:$( minikube ip )" -i http://fapp.sbebe.ch
