apiVersion: sloth.sbebe.ch/v1alpha1
kind: Sloth-Application
metadata:
  labels:
    app.kubernetes.io/name: sloth-application
    app.kubernetes.io/instance: sloth-application-sample
    app.kubernetes.io/part-of: sloth-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sloth-operator
  name: sloth-application-sample
spec:
  # TODO(user): Add fields here
