# permissions for end users to view fns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fns-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fauli-operator
    app.kubernetes.io/part-of: fauli-operator
    app.kubernetes.io/managed-by: kustomize
  name: fns-viewer-role
rules:
- apiGroups:
  - fauli.sbebe.ch
  resources:
  - fns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fauli.sbebe.ch
  resources:
  - fns/status
  verbs:
  - get
